### ISSUE TITLE
NAS2D/Common.h is deprecated. Replace inclusion with new headers.

### ISSUE THREAD

**Issue by cugone** [ldicker83/OPHD#111]
`NAS2D/Common.h` is now deprecated in favor of separate headers:

`NAS2D/StringUtils.h`
`NAS2D/MathUtils.h`
`NAS2D/Version.h`

`Common.h` will be removed in a future release. Suggest replacing all `#include Common.h` with whichever of the above headers is appropriate.

**Comment by cugone** [comment]
Is this issue now closed via #139 ?

**Comment by DanRStevens** [comment]
Huh, well, #139 didn't make any changes in that regards, since it only updated includes to `NAS2D.h`. Though I didn't notice any includes of any other NAS2D header files, other than in `main.cpp`.

Indeed, a quick grep of the source shows there are no includes for `NAS2D/Common.h`, and `main.cpp` was the only file that included anything other than `NAS2D.h` before the #139 update.

So yes, in that respect, this issue is closed now. Thank you for pointing that out.
